### ISSUE TITLE
Can't install - no stable version

### ISSUE THREAD

**Issue by Josh5A** [jdecool/ollama-php-client#3]
This is what I get when I try: 

% composer require jdecool/ollama-client
                                                                                                                             
  [InvalidArgumentException]                                                                                                                       
  Could not find a version of package jdecool/ollama-client matching your minimum-stability (stable). Require it with an explicit version constra  
  int allowing its desired stability.

**Comment by jdecool** [comment]
I've just tagged a [0.1.0](https://github.com/jdecool/ollama-php-client/releases/tag/0.1.0)
